version: '3.8'

services:
  debug:
    image: debug:latest
    container_name: debug
    restart: unless-stopped
    networks:
      - proxy-network

  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - proxy-network

networks:
  proxy-network:
    enable_ipv6: true

volumes:
  caddy_data:
  caddy_config: